/*
 * This file is generated by jOOQ.
 */
package crawlmanager.models;


import crawlmanager.models.tables.JobHistory;
import crawlmanager.models.tables.Jobs;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>crawl_jobs</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index JOBS_PRIMARY = Indexes0.JOBS_PRIMARY;
    public static final Index JOB_HISTORY_JOBID = Indexes0.JOB_HISTORY_JOBID;
    public static final Index JOB_HISTORY_PRIMARY = Indexes0.JOB_HISTORY_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index JOBS_PRIMARY = Internal.createIndex("PRIMARY", Jobs.JOBS, new OrderField[] { Jobs.JOBS.ID }, true);
        public static Index JOB_HISTORY_JOBID = Internal.createIndex("jobid", JobHistory.JOB_HISTORY, new OrderField[] { JobHistory.JOB_HISTORY.JOBID }, false);
        public static Index JOB_HISTORY_PRIMARY = Internal.createIndex("PRIMARY", JobHistory.JOB_HISTORY, new OrderField[] { JobHistory.JOB_HISTORY.ID }, true);
    }
}
