/*
 * This file is generated by jOOQ.
 */
package crawlmanager.models;


import crawlmanager.models.tables.JobHistory;
import crawlmanager.models.tables.Jobs;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in crawl_jobs
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>crawl_jobs.jobs</code>.
     */
    public static final Jobs JOBS = crawlmanager.models.tables.Jobs.JOBS;

    /**
     * The table <code>crawl_jobs.job_history</code>.
     */
    public static final JobHistory JOB_HISTORY = crawlmanager.models.tables.JobHistory.JOB_HISTORY;
}
