/*
 * This file is generated by jOOQ.
 */
package crawlmanager.models.tables;


import crawlmanager.models.CrawlJobs;
import crawlmanager.models.Indexes;
import crawlmanager.models.Keys;
import crawlmanager.models.tables.records.JobsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jobs extends TableImpl<JobsRecord> {

    private static final long serialVersionUID = 1625515317;

    /**
     * The reference instance of <code>crawl_jobs.jobs</code>
     */
    public static final Jobs JOBS = new Jobs();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<JobsRecord> getRecordType() {
        return JobsRecord.class;
    }

    /**
     * The column <code>crawl_jobs.jobs.id</code>.
     */
    public final TableField<JobsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>crawl_jobs.jobs.jobname</code>.
     */
    public final TableField<JobsRecord, String> JOBNAME = createField("jobname", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>crawl_jobs.jobs.process</code>.
     */
    public final TableField<JobsRecord, String> PROCESS = createField("process", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>crawl_jobs.jobs.arguments</code>.
     */
    public final TableField<JobsRecord, String> ARGUMENTS = createField("arguments", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>crawl_jobs.jobs.active</code>.
     */
    public final TableField<JobsRecord, Boolean> ACTIVE = createField("active", org.jooq.impl.SQLDataType.BIT.defaultValue(org.jooq.impl.DSL.inline("b'1'", org.jooq.impl.SQLDataType.BIT)), this, "");

    /**
     * The column <code>crawl_jobs.jobs.timeout_millis</code>.
     */
    public final TableField<JobsRecord, Integer> TIMEOUT_MILLIS = createField("timeout_millis", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>crawl_jobs.jobs.pause_millis</code>.
     */
    public final TableField<JobsRecord, Integer> PAUSE_MILLIS = createField("pause_millis", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>crawl_jobs.jobs.update_on</code>.
     */
    public final TableField<JobsRecord, Timestamp> UPDATE_ON = createField("update_on", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>crawl_jobs.jobs.created_on</code>.
     */
    public final TableField<JobsRecord, Timestamp> CREATED_ON = createField("created_on", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0000-00-00 00:00:00", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>crawl_jobs.jobs</code> table reference
     */
    public Jobs() {
        this(DSL.name("jobs"), null);
    }

    /**
     * Create an aliased <code>crawl_jobs.jobs</code> table reference
     */
    public Jobs(String alias) {
        this(DSL.name(alias), JOBS);
    }

    /**
     * Create an aliased <code>crawl_jobs.jobs</code> table reference
     */
    public Jobs(Name alias) {
        this(alias, JOBS);
    }

    private Jobs(Name alias, Table<JobsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Jobs(Name alias, Table<JobsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Jobs(Table<O> child, ForeignKey<O, JobsRecord> key) {
        super(child, key, JOBS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return CrawlJobs.CRAWL_JOBS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.JOBS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<JobsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_JOBS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<JobsRecord> getPrimaryKey() {
        return Keys.KEY_JOBS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<JobsRecord>> getKeys() {
        return Arrays.<UniqueKey<JobsRecord>>asList(Keys.KEY_JOBS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Jobs as(String alias) {
        return new Jobs(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Jobs as(Name alias) {
        return new Jobs(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Jobs rename(String name) {
        return new Jobs(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Jobs rename(Name name) {
        return new Jobs(name, null);
    }
}
