/*
 * This file is generated by jOOQ.
 */
package crawlmanager.models.tables.records;


import crawlmanager.models.tables.JobHistory;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JobHistoryRecord extends UpdatableRecordImpl<JobHistoryRecord> implements Record8<Integer, Integer, Integer, String, Timestamp, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = 664815173;

    /**
     * Setter for <code>crawl_jobs.job_history.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>crawl_jobs.job_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>crawl_jobs.job_history.jobid</code>.
     */
    public void setJobid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>crawl_jobs.job_history.jobid</code>.
     */
    public Integer getJobid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>crawl_jobs.job_history.crawl_state</code>.
     */
    public void setCrawlState(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>crawl_jobs.job_history.crawl_state</code>.
     */
    public Integer getCrawlState() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>crawl_jobs.job_history.message</code>.
     */
    public void setMessage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>crawl_jobs.job_history.message</code>.
     */
    public String getMessage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>crawl_jobs.job_history.update_on</code>.
     */
    public void setUpdateOn(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>crawl_jobs.job_history.update_on</code>.
     */
    public Timestamp getUpdateOn() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>crawl_jobs.job_history.start_time</code>.
     */
    public void setStartTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>crawl_jobs.job_history.start_time</code>.
     */
    public Timestamp getStartTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>crawl_jobs.job_history.end_time</code>.
     */
    public void setEndTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>crawl_jobs.job_history.end_time</code>.
     */
    public Timestamp getEndTime() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>crawl_jobs.job_history.created_on</code>.
     */
    public void setCreatedOn(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>crawl_jobs.job_history.created_on</code>.
     */
    public Timestamp getCreatedOn() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, String, Timestamp, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, Integer, Integer, String, Timestamp, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return JobHistory.JOB_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return JobHistory.JOB_HISTORY.JOBID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return JobHistory.JOB_HISTORY.CRAWL_STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return JobHistory.JOB_HISTORY.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return JobHistory.JOB_HISTORY.UPDATE_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return JobHistory.JOB_HISTORY.START_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return JobHistory.JOB_HISTORY.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return JobHistory.JOB_HISTORY.CREATED_ON;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getJobid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getCrawlState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdateOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getJobid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getCrawlState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdateOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getStartTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatedOn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value2(Integer value) {
        setJobid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value3(Integer value) {
        setCrawlState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value4(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value5(Timestamp value) {
        setUpdateOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value6(Timestamp value) {
        setStartTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value7(Timestamp value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord value8(Timestamp value) {
        setCreatedOn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public JobHistoryRecord values(Integer value1, Integer value2, Integer value3, String value4, Timestamp value5, Timestamp value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached JobHistoryRecord
     */
    public JobHistoryRecord() {
        super(JobHistory.JOB_HISTORY);
    }

    /**
     * Create a detached, initialised JobHistoryRecord
     */
    public JobHistoryRecord(Integer id, Integer jobid, Integer crawlState, String message, Timestamp updateOn, Timestamp startTime, Timestamp endTime, Timestamp createdOn) {
        super(JobHistory.JOB_HISTORY);

        set(0, id);
        set(1, jobid);
        set(2, crawlState);
        set(3, message);
        set(4, updateOn);
        set(5, startTime);
        set(6, endTime);
        set(7, createdOn);
    }
}
